# Dockerfile for universalresolver/base-alpine

FROM openjdk:8-alpine
MAINTAINER Markus Sabadello <markus@danubetech.com>

USER root

RUN apk update && apk upgrade && \
    apk add --no-cache maven git

ENV PATH $JAVA_HOME/bin:$PATH

ADD ./resolver/java/ /opt/uni-resolver-java

RUN cd /opt/uni-resolver-java && mvn clean install -N -DskipTests && mvn clean && \
    cd /opt/uni-resolver-java/uni-resolver-core && mvn clean install -N -DskipTests && mvn clean && \
    cd /opt/uni-resolver-java/driver && mvn clean install -N -DskipTests && mvn clean
